apiVersion: v1
kind: DeploymentConfig
metadata:
  name: app
spec:
  strategy:
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: Retry
        execNewPod:
          command:
            - bin/console
            - 'doctrine:migrations:migrate'
          containerName: app
  triggers:
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - app
        from:
          kind: ImageStreamTag
          name: 'app:latest'
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - web
        from:
          kind: ImageStreamTag
          name: 'web:latest'
    -
      type: ConfigChange
  replicas: 1
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      volumes:
        -
          name: public
          emptyDir: {  }
      containers:
        -
          name: app
          image: 'symfony/app'
          ports:
            -
              containerPort: 9000
              protocol: TCP
          env:
            -
              name: SYMFONY__DATABASE_HOST
              value: mysql
            -
              name: SYMFONY__DATABASE_NAME
              value: symfony
            -
              name: SYMFONY__DATABASE_USER
              value: userB88
            -
              name: SYMFONY__DATABASE_PASSWORD
              value: YvEFkHOhoKEJGihs
          volumeMounts:
            -
              name: public
              mountPath: /var/www/html/public
        -
          name: web
          image: 'symfony/web'
          ports:
            -
              containerPort: 80
              protocol: TCP
          env:
            -
              name: FPM_HOST
              value: localhost
          volumeMounts:
            -
              name: public
              mountPath: /var/www/html/public
